<div class="slider">
    <ol class="breadcrumb">
        <li><a href="<?= URL('/') ?>">首页</a></li>
        <li class="active"><?= T('产品列表') ?></li>
    </ol>
    <form method="POST" action="<?= URL('/products', $get_form) ?>" id="products-search">
        <div class="row">
            <div class="col-xs-12 col-md-8 ">
                <div class="input-group">
                    <input type="text" class="form-control" name="title" placeholder="请输入产品名称或者编号" value="<?= $form['title'] ?>" />
                    <div class="input-group-addon">
                        <button class="none" type="submit" form='products-search'><i class="fa fa-search fa-fw"></i> 搜索</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <div class="hr"></div>
    <div class="search_tags">
        <span class="desc">产品类型</span>
        <a href="<?= URL('/products', array_merge($get_form, ['type' => 0])) ?>" class="<?= !$get_form['type'] ? 'active' : ''?>">全部</a>
        <?php foreach(\Gini\ORM\Product::$TYPE as $k => $v): ?>
            <a href="<?= URL('/products', array_merge($get_form, ['type' => (int)$k])) ?>" class="<?= $get_form['type'] == $k ? 'active' : ''?>"><?= $v ?></a>
        <?php endforeach; ?>
    </div>
    <div class="hr"></div>
    <div class="search_tags">
        <span class="desc">产品状态</span>
        <a href="<?= URL('/products', array_merge($get_form, ['status' => 0])) ?>" class="<?= !$get_form['status'] ? 'active' : ''?>">全部</a>
        <?php foreach(\Gini\ORM\Product::$STATUS as $k => $v): ?>
            <a href="<?= URL('/products', array_merge($get_form, ['status' => (int)$k])) ?>" class="<?= $get_form['status'] == $k ? 'active' : ''?>"><?= $v ?></a>
        <?php endforeach; ?>
    </div>
</div>
<div class="hr_2"></div>
<div class="products">
    <table class="table table-hover">
        <tbody>
            <?php foreach($products as $product): ?>
            <tr>
                <td class="col-md-4 col-xs-6">
                    <a href="<?= URL("/product/{$product->id}") ?>"><p class="pro-name"><?= H($product->title) ?></p></a>
                    <span class="tag-in-table-title">销售中</span>
                </td>
                <td class="col-xs-2 hidden-xs">
                    <p class="pro-type">固定收益</p>
                </td>
                <td class="col-xs-2 hidden-xs">
                    <p class="pro-data"><?= (int)$product->dead_day ?>天</p>
                    <p class="pro-remark">期限</p>
                </td>
                <td class="hidden-xs">
                    <p class="pro-remark"><?= H($product->purchase) ?></p>
                </td>
                <td class="col-xs-2">
                    <p class="pro-btn text-right">
                        <a class="btn" href="<?= URL("/product/{$product->id}") ?>"><?= T('查看详情') ?></a>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>