<div class="slider">
    <ol class="breadcrumb">
        <li><a href="<?= URL('/') ?>">首页</a></li>
        <li><a href="<?= URL('/products') ?>">产品列表</a></li>
        <li class="active"><?= T('平安信托大名城2号集合资金信托计划') ?></li>
    </ol>
    <div class="hr"></div>
    <div class="profile-box">
        <div class="row">
            <div class="col-md-6">
                <div class="profile-content">
                    <div class="pub-tag">
                        <strong>预售期</strong>
                        <small>2018-09-20 12:00:00</small>
                        <div class="tag-shadow"></div>
                    </div>
                    <h2 class="name">平安信托大名城2号集合资金信托计划-526天</h2>
                    <h3 class="type">固定收益</h3>
                    <div class="row column-desc">
                        <div class="col-md-4 col-xs-12 column">
                            <h4>业绩比较基准</h4>
                            <p class="xm red">8.50<small>%</small></p>
                        </div>
                        <div class="col-md-4 col-xs-12 column">
                            <h4>期限</h4>
                            <p class="xm">526天</p>
                        </div>
                        <div class="col-md-4 col-xs-12 column">
                            <h4>起购（元）</h4>
                            <p class="xm">100万</p>
                        </div>
                    </div>
                    <div class="progress">
                        <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%"></div>
                    </div>
                    <div class="row column-time">
                        <div class="col-md-4 col-xs-12 column">
                            <h5>购买时间</h5>
                            <h6>2018-09-30</h6>
                        </div>
                        <div class="col-md-4 col-xs-12 column">
                            <h5>预计起息日</h5>
                            <h6>2018-10-07</h6>
                        </div>
                        <div class="col-md-4 col-xs-12 column">
                            <h5>预计到期日</h5>
                            <h6>2018-12-30</h6>
                        </div>
                    </div>
                    <div class="buttons row">
                        <div class="col-md-6 col-xs-12"><a class="btn btn-primary btn-block"><?= T('立即预约') ?></a></div>
                    </div>
                </div>
            </div>
            <div class="col-md-6"></div>
        </div>
    </div>
    <div class="hr_2"></div>
    <div class="profile-box">
        <div class="desc-box">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Home</a></li>
                <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Profile</a></li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="home">...</div>
                <div role="tabpanel" class="tab-pane" id="profile">222</div>
            </div>
        </div>
    </div>
    <div class="hr_2"></div>
</div>