<div class="slider">
    <ol class="breadcrumb">
        <li><a href="<?= URL('/') ?>">首页</a></li>
        <li><a href="<?= URL('/products') ?>">产品列表</a></li>
        <li class="active"><?= T('平安信托大名城2号集合资金信托计划') ?></li>
    </ol>
    <div class="hr"></div>
    <div class="profile-box">
        <div class="row">
            <div class="col-md-6">
                <div class="profile-content">
                    <div class="pub-tag">
                        <strong>预售期</strong>
                        <small><?= $product->open_day ?></small>
                        <div class="tag-shadow"></div>
                    </div>
                    <h2 class="name"><?= H($product->title) ?></h2>
                    <h3 class="type"><?= H($product->Issuer) ?></h3>
                    <div class="row column-desc">
                        <div class="col-md-4 col-xs-12 column">
                            <h4>业绩比较基准</h4>
                            <p class="xm red">8.50<small>%</small></p>
                        </div>
                        <div class="col-md-4 col-xs-12 column">
                            <h4>期限</h4>
                            <p class="xm"><?= (int)$product->dead_day ?>天</p>
                        </div>
                        <div class="col-md-4 col-xs-12 column">
                            <h4>起购（元）</h4>
                            <p class="xm"><?= H($product->purchase) ?></p>
                        </div>
                    </div>
                    <div class="progress">
                        <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%"></div>
                    </div>
                    <div class="row column-time">
                        <div class="col-md-4 col-xs-12 column">
                            <h5>购买时间</h5>
                            <h6><?= $product->open_day ?></h6>
                        </div>
                        <div class="col-md-4 col-xs-12 column">
                            <h5>预计起息日</h5>
                            <h6><?= date('Y-m-d H:i:s', strtotime($product->open_day) + 2 * 86400) ?></h6>
                        </div>
                        <div class="col-md-4 col-xs-12 column">
                            <h5>预计到期日</h5>
                            <h6><?= date('Y-m-d H:i:s', strtotime($product->open_day) + $product->dead_day * 86400) ?></h6>
                        </div>
                    </div>
                    <div class="buttons row">
                        <div class="col-md-6 col-xs-12"><a class="btn btn-primary btn-block"><?= T('立即预约') ?></a></div>
                    </div>
                </div>
            </div>
            <div class="col-md-6"></div>
        </div>
    </div>
    <div class="hr_2"></div>
    <div class="profile-box">
        <div class="desc-box">
            <div class="product-desc">
                <h3 class="title">基础信息</h3>
                <div class="row">
                    <div class="col-md-2 col-xs-4 bg">产品全称</div>
                    <div class="col-md-4 col-xs-8 body"><?= H($product->title) ?></div>
                    <div class="col-md-2 col-xs-4 bg">产品成立日</div>
                    <div class="col-md-4 col-xs-8 body"><?= H($product->create_day) ?></div>
                    <div class="col-md-2 col-xs-4 bg">产品期限</div>
                    <div class="col-md-4 col-xs-8 body"><?= (int)$product->dead_day ?>天</div>
                </div>
                <h3 class="title">购买规则</h3>
                <div class="row">
                    <div class="col-md-2 col-xs-4 bg">购买金额</div>
                    <div class="col-md-4 col-xs-8 body"><?= H($product->purchase) ?></div>
                    <div class="col-md-2 col-xs-4 bg">固定管理费</div>
                    <div class="col-md-4 col-xs-8 body"><?= H($product->admin_rate) ?></div>
                    <div class="col-md-2 col-xs-4 bg">购买对象</div>
                    <div class="col-md-4 col-xs-8 body"><?= H($product->purchase_object) ?></div>
                </div>
                <h3 class="title">分配规则</h3>
                <div class="row">
                    <div class="col-md-2 col-xs-4 bg">分配方式</div>
                    <div class="col-md-4 col-xs-8 body"><?= H($product->distribution) ?></div>
                    <div class="col-md-2 col-xs-4 bg">赎回费率</div>
                    <div class="col-md-4 col-xs-8 body"><?= H($product->redemption_rate) ?></div>
                </div>
            </div>
        </div>
    </div>
    <div class="hr_2"></div>
</div>