<div class="slider">
    <ol class="breadcrumb">
        <li><a href="<?= URL('/') ?>">首页</a></li>
        <li><a href="<?= URL('/products') ?>">产品列表</a></li>
        <li class="active"><?= T('平安信托大名城2号集合资金信托计划') ?></li>
    </ol>
    <div class="hr"></div>
    <div class="profile-box">
        <div class="row">
            <div class="col-md-6">
                <div class="profile-content">
                    <div class="pub-tag">
                        <strong>开放日</strong>
                        <small><?= $product->open_day ?></small>
                        <div class="tag-shadow"></div>
                    </div>
                    <h2 class="name"><?= H($product->title) ?></h2>
                    <h3 class="type"><?= H($product->Issuer) ?> <strong class="red"><?= number_format($product->amount) ?>元</strong></h3>
                    <div class="row column-desc">
                        <div class="col-md-4 col-xs-12 column">
                            <h4>收益率</h4>
                            <p class="xm red"><?= $product->rate ?: '0.00' ?><small>%</small></p>
                        </div>
                        <div class="col-md-4 col-xs-12 column">
                            <h4>期限</h4>
                            <p class="xm"><?= (int)$product->dead_day ?>天</p>
                        </div>
                        <div class="col-md-4 col-xs-12 column">
                            <h4>起购（元）</h4>
                            <p class="xm"><?= H($product->purchase / 10000) ?>万</p>
                        </div>
                    </div>
                    <div class="progress">
                        <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
                    </div>
                    <div class="row column-time">
                        <div class="col-md-4 col-xs-12 column">
                            <h5>预计开放日</h5>
                            <h6><?= $product->open_day ?></h6>
                        </div>
                        <div class="col-md-4 col-xs-12 column">
                            <h5>预计购买日</h5>
                            <h6><?= $product->open_day ?></h6>
                        </div>
                        <div class="col-md-4 col-xs-12 column">
                            <h5>预计到期日</h5>
                            <h6><?= date('Y-m-d H:i:s', strtotime($product->open_day) + $product->dead_day * 86400) ?></h6>
                        </div>
                    </div>
                    <div class="buttons row">
                        <div class="col-md-6 col-xs-12">
                            <a class="btn btn-primary btn-block" href="gini-ajax:ajax/product/reserve/<?= (int)$product->id ?>"><?= T('立即预约') ?></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div style="padding-top: 60px;"><div class="circleChart"></div></div>
            </div>
        </div>
    </div>
    <div class="hr_2"></div>
    <div class="profile-box">
        <div class="desc-box">
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">产品详情</a></li>
                <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">产品公告</a></li>
            </ul>
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="home">
                    <div class="product-desc">
                        <h3 class="title">基础信息</h3>
                        <div class="row">
                            <div class="col-md-2 col-xs-4 bg">产品全称</div>
                            <div class="col-md-4 col-xs-8 body"><?= H($product->title) ?></div>
                            <div class="col-md-2 col-xs-4 bg">产品成立日</div>
                            <div class="col-md-4 col-xs-8 body"><?= H($product->create_day) ?></div>
                            <div class="col-md-2 col-xs-4 bg">产品期限</div>
                            <div class="col-md-4 col-xs-8 body"><?= (int)$product->dead_day ?>天</div>
                        </div>
                        <h3 class="title">购买规则</h3>
                        <div class="row">
                            <div class="col-md-2 col-xs-4 bg">起购金额</div>
                            <div class="col-md-4 col-xs-8 body"><?= H($product->purchase / 10000) ?>万</div>
                            <div class="col-md-2 col-xs-4 bg">固定管理费</div>
                            <div class="col-md-4 col-xs-8 body"><?= H($product->admin_rate) ?></div>
                            <div class="col-md-2 col-xs-4 bg">购买对象</div>
                            <div class="col-md-4 col-xs-8 body"><?= H($product->purchase_object) ?></div>
                        </div>
                        <h3 class="title">分配规则</h3>
                        <div class="row">
                            <div class="col-md-2 col-xs-4 bg">分配方式</div>
                            <div class="col-md-4 col-xs-8 body"><?= H($product->distribution) ?></div>
                            <div class="col-md-2 col-xs-4 bg">赎回费率</div>
                            <div class="col-md-4 col-xs-8 body"><?= H($product->redemption_rate) ?></div>
                        </div>
                    </div>
                </div>
                <div role="tabpanel" class="tab-pane" id="profile">
                    <div class="product-desc product-news">
                        <ul class="list">
                            <?php
                                foreach($news as $new): 
                            ?>
                            <li>
                                <a href="<?= URL("/news/profile/{$new->id}") ?>"><?= H($new->title) ?></a>
                                <div class="hr"></div>
                                <p class="time"><?= $new->ctime ?></p>
                            </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="hr_2"></div>
    <?php $float = sprintf('%.2f', ($product->amount - $product->balance) / $product->amount * 100) ; ?>
</div>
<script>
require(['main'], function($){
    require(['circleChart'], function(){
        $(".circleChart").circleChart({
            color: '#F4610C',
            value: <?= $float ?>,
            text: '<?= $float ?>' + '%',
            startAngle: 75,
            speed: 1000,
            widthRatio: 0.2,
            size: 220,
            animation: "easeInOutCubic"
        });
    })
})
</script>