---
user:
  name: '用户管理' 
  perms:
  - '添加用户'
  - '修改用户密码'
  - '修改用户基本信息'
  - '修改用户角色'
  - '删除用户'
role:
  name: '权限管理' 
  perms:
  - '查看权限管理模块'
  - '添加角色'
  - '删除角色'
  - '修改角色权限'
group:
  name: '机构管理'
  perms:
  - '查看机构管理'
  - '修改机构信息'
record:
  name: '档案管理'
  perms:
  - '查看档案模块'
  - '查看档案项目内容'
template:
  name: '模板信息'
  perms:
  - '查看模板信息模块'
  - '添加新模板'
  - '修改模板信息'
  - '删除模板信息'
project:
  name: '项目模块'
  perms:
  - '查看项目模块'
  - '添加新项目'
  - '删除项目'
  - '修改项目基础信息'
  - '指派派件员'
  - '指派估价师'
  - '指派查勘员'
  - '克隆其他项目数据'
  - '打印项目报告'
  - '归档项目'
approval:
  name: '审核功能'
  perms:
  - '提交审核'
  - '部门内审核（一审）'
  - '审核部审核（二审）'
  - '财务审核（登记）'
  - '办公室审核（终审）'
...