<div class="slider">
    <?php $me = _G('ME'); ?>
    <ol class="breadcrumb">
        <li><a href="<?= URL('/') ?>">首页</a></li>
        <li><a href="<?= URL('/mine') ?>"><?= T('个人中心') ?></a></li>
        <li><?= T('管理中心') ?></li>
    </ol>
    <div class="row">
        <div class="col-md-2">
            <?= V('admin/sidebar', ['active' => $active]) ?>
        </div>
        <div class="col-md-10">
            <div class="admin-container">
                <h1 class="title"><span></span><?= T('合同管理') ?></h1>
                <div class="hr"></div>
            </div>
        </div>
    </div>
    <div class="hr_2"></div>
</div>