<div class="slider">
    <?php $me = _G('ME'); ?>
    <ol class="breadcrumb">
        <li><a href="<?= URL('/') ?>">首页</a></li>
        <li><a href="<?= URL('/mine') ?>"><?= T('个人中心') ?></a></li>
        <li><?= T('管理中心') ?></li>
    </ol>
    <div class="row">
        <div class="col-md-2">
            <?= V('admin/sidebar', ['active' => $active]) ?>
        </div>
        <div class="col-md-10">
            <?= V('confirm') ?>
            <div class="admin-container">
                <h1 class="title">
                    <span></span>合同管理
                    <p class="title-button">
                        <a href="gini-ajax:ajax/agreement/add"><i class="fa fa-fw fa-plus"></i></a>
                    </p>
                </h1>
                <form class="form-horizontal" action="<?= URL('') ?>">
                    <div class="row">
                        <div class="col-xs-12 col-md-6">
                            <input type="text" class="form-control" name="phone" placeholder="请输入手机号码" value="<?= $form['phone'] ?>" />
                        </div>
                        <div class="col-xs-12  col-md-6">
                            <input type="text" class="form-control" name="number" placeholder="请输入产品编号" value="<?= $form['number'] ?>" />
                        </div>
                    </div>
                    <div class="hr"></div>
                    <div class="row">
                        <div class="col-xs-12 col-md-6">
                            <button class="btn btn-ok btn-raised" type="submit"><i class="fa fa-search fa-fw"></i> 搜索</button>
                        </div>
                    </div>
                </form>
                <div class="hr"></div>
                <table class="table table-hover">
                    <tbody>
                        <tr class="bg bg-primary">
                            <td class="hidden-xs"><?= T('合同编号') ?></td>
                            <td><?= T('姓名') ?></td>
                            <td class="hidden-xs"><?= T('产品名称') ?></td>
                            <td><?= T('出资金额') ?></td>
                            <td></td>
                        </tr>
                    </tbody>
                    <tbody>
                        <?php if (!count($agreements)): ?>
                            <tr>
                                <td colspan="5"><p class="text-center red"><?= T('未查询到合同!') ?></p></td>
                            </tr>
                        <?php
                            else: foreach($agreements as $agreement): 
                        ?>
                            <tr>
                                <td class="hidden-xs"><?= H($agreement->product->number) ?></td>
                                <td><?= $agreement->user->name ?></td>
                                <td class="hidden-xs"><?= H($agreement->product->title) ?></td>
                                <td><span class="red"><?= strtr('￥%amount.00', ['%amount' => $agreement->amount]) ?></span></td>
                                <td>
                                    <a href="gini-ajax:ajax/agreement/edit/<?= (int)$agreement->id ?>"><i class="fa fa-fw fa-edit"></i></a>
                                    <a 
                                        data-confirm="<?= H(T('您确认删除合同:agreement吗?', [':agreement'=>$agreement->id])) ?>"
                                        data-confirm-description="<?= H(T('点击确认后会删除该合同信息, 请谨慎处理!')) ?>"
                                        href="gini-ajax:ajax/agreement/delete/<?= (int)$agreement->id ?>"><i class="fa fa-fw fa-close"></i></a>
                                </td>
                            </tr>
                        <?php endforeach; endif;?>
                    </tbody>
                </table>
                <?= $pagination ?>
            </div>
        </div>
    </div>
    <div class="hr_2"></div>
</div>