<div class="slider">
    <?php $me = _G('ME'); ?>
    <ol class="breadcrumb">
        <li><a href="<?= URL('/') ?>">首页</a></li>
        <li><a href="<?= URL('/mine') ?>"><?= T('个人中心') ?></a></li>
        <li><?= T('产品中心') ?></li>
    </ol>
    <div class="row">
        <div class="col-md-2">
            <?= V('admin/sidebar', ['active' => $active]) ?>
        </div>
        <div class="col-md-10">
            <?= V('confirm') ?>
            <div class="admin-container">
                <h1 class="title">
                    <span></span>产品列表
                    <p class="title-button">
                        <a href="gini-ajax:ajax/product/add"><i class="fa fa-fw fa-plus"></i></a>
                    </p>
                </h1>
                <div class="tabs-container">
                    <?php foreach(\Gini\ORM\Product::$PUBLISH as $key => $v): ?>
                        <a href="<?= URL('/manage/product/'.$key) ?>"><span class="label label-<?= $key == $publish ? 'info' : 'default' ?>"><?= $v ?></span></a>
                    <?php endforeach; ?>
                </div>
                <form class="form-horizontal" action="<?= URL('') ?>">
                    <div class="row">
                        <div class="col-xs-12 col-md-6">
                            <input type="text" class="form-control" name="number" placeholder="请输入产品编号" value="<?= $form['number'] ?>" />
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <button class="btn btn-ok btn-raised" type="submit"><i class="fa fa-search fa-fw"></i> 搜索</button>
                        </div>
                    </div>
                </form>
                <div class="hr"></div>
                <table class="table table-hover">
                    <tbody>
                        <tr class="bg bg-primary">
                            <td><?= T('产品全称') ?></td>
                            <td class="hidden-xs"><?= T('产品成立日') ?></td>
                            <td><?= T('产品期限') ?></td>
                            <td class="hidden-xs"><?= T('发行方') ?></td>
                            <td></td>
                        </tr>
                    </tbody>
                    <tbody>
                        <?php if (!count($products)): ?>
                            <tr>
                                <td colspan="5"><p class="text-center red"><?= T('未查询到匹配的产品!') ?></p></td>
                            </tr>
                        <?php
                            else: foreach($products as $product): 
                        ?>
                            <tr>
                                <td><?= H($product->title) ?></td>
                                <td class="hidden-xs"><?= T($product->create_day) ?></td>
                                <td><?= T('%dead 天', ['%dead' => $product->dead_day]) ?></td>
                                <td class="hidden-xs"><?= T($product->Issuer) ?></td>
                                <td class="text-right">
                                    <a href="gini-ajax:ajax/product/edit/<?= (int)$product->id ?>" title="编辑"><i class="fa fa-fw fa-edit"></i></a>
                                    <?php if($product->publish != 1 && $me->isAllowedTo('超级管理')): ?>
                                        <a 
                                            data-confirm="<?= H(T('您确认审批发布产品:product吗?', [':product'=>$product->title])) ?>"
                                            data-confirm-description="<?= H(T('点击确认后产品信息将会发布到首页, 请谨慎处理!')) ?>"
                                            href="gini-ajax:ajax/product/approval/<?= (int)$product->id ?>"
                                            title="审批"><i class="fa fa-fw fa-level-up"></i></a>
                                    <?php endif; ?>
                                    <?php if($product->publish == 1 && $me->isAllowedTo('超级管理')): ?>
                                        <a 
                                            data-confirm="<?= H(T('您确认审批下架产品:product吗?', [':product'=>$product->title])) ?>"
                                            data-confirm-description="<?= H(T('点击确认后产品信息将会下架过期, 不显示在首页, 请谨慎处理!')) ?>"
                                            href="gini-ajax:ajax/product/unapproval/<?= (int)$product->id ?>"
                                            title="过期下架"><i class="fa fa-fw fa-level-down"></i></a>
                                    <?php endif; ?>
                                    <?php if($product->publish == 0 || $me->isAllowedTo('超级管理')): ?>
                                    <a 
                                        data-confirm="<?= H(T('您确认删除产品:product吗?', [':product'=>$product->title])) ?>"
                                        data-confirm-description="<?= H(T('点击确认后会删除该产品信息, 请谨慎处理!')) ?>"
                                        href="gini-ajax:ajax/product/delete/<?= (int)$product->id ?>"
                                        title="删除"><i class="fa fa-fw fa-close"></i></a>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; endif;?>
                    </tbody>
                </table>
                <?= $pagination ?>
            </div>
        </div>
    </div>
    <div class="hr_2"></div>
</div>