<div class="list-group">
    <a href="<?= URL('/manage') ?>" class="list-group-item <?= $active == 'users' ? 'active' : ''?>"><?= T('用户管理') ?></a>
    <a href="<?= URL('/manage/banner') ?>" class="list-group-item <?= $active == 'banner' ? 'active' : ''?>"><?= T('首页轮播') ?></a>
    <a href="<?= URL('/manage/product') ?>" class="list-group-item <?= $active == 'product' ? 'active' : ''?>"><?= T('产品管理') ?></a>
    <a href="<?= URL('/manage/agreement') ?>" class="list-group-item <?= $active == 'agreement' ? 'active' : ''?>"><?= T('合同管理') ?></a>
    <a href="<?= URL('/manage/news') ?>" class="list-group-item <?= $active == 'news' ? 'active' : ''?>"><?= T('新闻公告') ?></a>
    <a href="<?= URL('/manage/about') ?>" class="list-group-item <?= $active == 'about' ? 'active' : ''?>"><?= T('联系我们') ?></a>
    <a href="<?= URL('/manage/reserve') ?>" class="list-group-item <?= $active == 'reserve' ? 'active' : ''?>"><?= T('预约信息') ?></a>
</div>