<div id="add-news-modal" class="modal fade in">
<div class="modal-dialog"><div class="modal-content">
    <div class="modal-header">
        <div class="alert alert-dismissible alert-primary">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title"><?= H(T('添加公告')) ?></h4>
        </div>
    </div>
    <div class="modal-body" style="padding-top:20px;">
        <form id="add-news-form" method="POST" action="gini-ajax:ajax/news/add">
            <div class="row">
                <div class="col-md-6 col-xs-12">
                    <div class="form-group <?= isset($form['_errors']['title']) ? ' has-error':'' ?>">
                        <?php if (isset($form['_errors']['title'])) { ?>
                        <span class="label label-danger pull-right">
                            <?= H($form['_errors']['title']) ?>
                        </span>
                        <?php } ?>
                        <label class="control-label" for="title"><?= H('公告标题') ?></label>
                        <input id="title" name="title" type="text" class="form-control" value="<?= H($form['title']) ?>"/>
                    </div>
                </div>
                <div class="col-md-6 col-xs-12">
                    <div class="form-group label-floating is-empty">
                        <?php if (isset($form['_errors']['type'])) { ?>
                        <span class="badge badge-danger pull-right">
                            <?= H($form['_errors']['type']) ?>
                        </span>
                        <?php } ?>
                        <label class="control-label" for="type"><?= H('公告类型') ?></label>
                        <select class="selectpicker form-control <?= isset($form['_errors']['type']) ? 'is-invalid' : '' ?>" name="type" id="type" size="1">
                            <?php foreach (\Gini\ORM\News::$TYPE as $k => $v): ?>
                                <option value="<?= T($k) ?>" <?= $form['type'] == $k ? "selected" : '' ?>><?= T($v) ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 col-xs-12">
                    <div class="form-group <?= isset($form['_errors']['product']) ? ' has-error':'' ?>">
                        <?php if (isset($form['_errors']['product'])) { ?>
                        <span class="label label-danger pull-right">
                            <?= H($form['_errors']['product']) ?>
                        </span>
                        <?php } ?>
                        <label class="control-label" for="product"><?= H('关联产品') ?><small class="red">（<?= H('公告类型为产品公告可选择关联产品信息') ?>）</small></label>
                        <input id="product" name="product" type="text" class="form-control autocomplete" autocomplete="off" value="<?= H($form['product']) ?>" placeholder="<?= T('请输入产品编号或名称') ?>"/>
                        <input id="product_id" name="product_id" hidden value="<?= $form['product_id'] ?>" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="control-label" for="content"><?= H('内容') ?></label>
                        <?= V('coder', [
                            'name' => 'content',
                            'content' => $form['content']
                        ])?>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <div class="col-md-12">
            <button class="btn btn-save btn-raised" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times fa-fw "></i><?= H(T('关闭')) ?></button>
            <button class="btn btn-ok btn-raised" form="add-news-form" type="submit"><i class="fa fa-plus fa-fw"></i> <?= H(T('添加')) ?></button>
        <div class="row">
    </div>
</div></div>
</div>
<script data-ajax="true">
require(['main', 'bootstrap.autocomplete'], function($){

    var $modal = $('#add-news-modal');
    $modal
    .on('hidden.bs.modal', function(){
        $modal.remove();
    })
    .modal();

    $('#add-news-form').on('ajax-success', function(){
        $modal
        .removeAttr('id').modal('hide')
        .find('[id]').removeAttr('id');
    });

    require(['bootstrap-select', 'css!../css/bootstrap-select'], function(){
        $('.selectpicker').selectpicker()
    })

    $('input#product').autocomplete({
        source: function(query, process){
            $.ajax({
                url: 'ajax/product/getProducts',
                method: 'POST',
                data: {
                    query: query
                },
                success: function(respData) {
                    return process(respData)
                }
            })
        },
        formatItem: function(item){
            return item["name"] + '(' + item["number"] + ')'
        },
        setValue: function(item){
            return { 'data-value': item["name"], 'real-value': item["id"] }
        },
        select: function () {
            var val = this.$menu.find('.active').attr('data-value'),
                realVal = this.$menu.find('.active').attr('real-value')
            this.$element
            .val(this.updater(val))
            .attr("real-value", realVal)
            .change()
            $('input#product_id').val(realVal)
            return this.hide()
        }
    });
});