<div id="edit-news-modal" class="modal fade in">
<div class="modal-dialog"><div class="modal-content">
    <div class="modal-header">
        <div class="alert alert-dismissible alert-primary">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title"><?= H(T('修改新闻公告')) ?></h4>
        </div>
    </div>
    <div class="modal-body" style="padding-top:20px;">
        <form id="edit-news-form" method="POST" action="gini-ajax:ajax/news/edit/<?= (int)$new->id ?>">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group <?= isset($form['_errors']['title']) ? ' has-error':'' ?>">
                        <?php if (isset($form['_errors']['title'])) { ?>
                        <span class="label label-danger pull-right">
                            <?= H($form['_errors']['title']) ?>
                        </span>
                        <?php } ?>
                        <label class="control-label" for="title"><?= H('新闻标题') ?></label>
                        <input id="title" name="title" type="text" class="form-control" value="<?= H($form['_errors'] ? $form['title'] : $new->title) ?>"/>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="control-label" for="content"><?= H('内容') ?></label>
                        <?= V('coder', [
                            'name' => 'content',
                            'content' => $form['_errors'] ? $form['content'] : $new->content
                        ])?>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <div class="col-md-12">
            <button class="btn btn-save btn-raised" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times fa-fw "></i><?= H(T('关闭')) ?></button>
            <button class="btn btn-ok btn-raised" form="edit-news-form" type="submit"><i class="fa fa-save fa-fw"></i> <?= H(T('保存')) ?></button>
        <div class="row">
    </div>
</div></div>
</div>
<script data-ajax="true">
require(['main'], function($){

    var $modal = $('#edit-news-modal');
    $modal
    .on('hidden.bs.modal', function(){
        $modal.remove();
    })
    .modal();

    $('#edit-news-form').on('ajax-success', function(){
        $modal
        .removeAttr('id').modal('hide')
        .find('[id]').removeAttr('id');
    });

    require(['bootstrap-select', 'css!../css/bootstrap-select'], function(){
        $('.selectpicker').selectpicker()
    })
});