<div class="slider">
    <ol class="breadcrumb">
        <li><a href="<?= URL('/') ?>">首页</a></li>
        <li class="active"><?= T('新闻公告') ?></li>
    </ol>
    <div class="news-content">
        <h1 class="title"><span></span>新闻公告</h1>
        <ul class="list">
            <?php
                $news = those('news')->orderBy('ctime', 'D'); 
                foreach($news as $new): 
                    $content = preg_replace(['/<script.*>(.*)<\/script>/siU', '/<style.*>(.*)<\/style>/siU'], ['', ''], $new->content);
                    $content = strip_tags($content);
                    $content = mb_substr($content, 1, 180);
            ?>
            <li>
                <a href="<?= URL("/news/profile/{$new->id}") ?>"><?= H($new->title) ?></a>
                <p class="desc"><?= $content ?></p>
                <p class="time"><?= $new->ctime ?></p>
            </li>
            <?php endforeach; ?>
        </ul>
        <?= $pagination ?>
    </div>
    <div class="hr"></div>
</div>