<div class="slider">
    <ol class="breadcrumb">
        <li><a href="<?= URL('/') ?>">首页</a></li>
        <li><a href="<?= URL('/news') ?>">新闻公告</a></li>
        <li class="active"><?= H($new->title) ?></li>
    </ol>
    <div class="news-content">
        <div class="info-header">
            <h1><?= H($new->title) ?></h1>
            <p><a href="<?= URL('/') ?>">煎饼理财</a><i>|</i><span><?= $new->ctime ?></span></p>
        </div>
        <div class="info-content" style="padding: 20px 0px;"><?= $new->content ?></div>
    </div>
</div>
<div class="hr_2"></div>