<div id="add-user-modal" class="modal fade in">
<div class="modal-dialog"><div class="modal-content">
    <div class="modal-header">
        <div class="alert alert-dismissible alert-primary">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title"><?= H(T('修改用户')) ?></h4>
        </div>
    </div>
    <div class="modal-body" style="padding-top:20px;">
        <form id="add-user-form" method="POST" action="gini-ajax:ajax/user/edit/<?= (int)$user->id ?>">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group <?= isset($form['_errors']['username']) ? ' has-error':'' ?>">
                    <?php if (isset($form['_errors']['username'])) { ?>
                    <span class="label label-danger pull-right">
                        <?= H($form['_errors']['username']) ?>
                    </span>
                    <?php } ?>
                    <label class="control-label" for="username"><?= H('登录账号') ?></label>
                    <input id="username" name="username" type="text" class="form-control" value="<?= $form['_errors'] ? H($form['username']) : H($user->username) ?>"/>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group <?= isset($form['_errors']['password']) ? ' has-error':'' ?>">
                    <?php if (isset($form['_errors']['password'])) { ?>
                    <span class="label label-danger pull-right">
                        <?= H($form['_errors']['password']) ?>
                    </span>
                    <?php } ?>
                    <label class="control-label" for="password"><?= H(T('密码')) ?></label>
                    <input id="password" name="password" type="password" class="form-control" autocomplete="off" value="" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group <?= isset($form['_errors']['name']) ? ' has-error':'' ?>">
                    <?php if (isset($form['_errors']['name'])) { ?>
                    <span class="label label-danger pull-right">
                        <?= H($form['_errors']['name']) ?>
                    </span>
                    <?php } ?>
                    <label class="control-label" for="name"><?= H(T('姓名')) ?></label>
                    <input id="name" name="name" type="text" class="form-control" autocomplete="off" value="<?= $form['_errors'] ? H($form['name']) : H($user->name) ?>" />
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group label-floating is-empty">
                    <label for="email" class="control-label"><?= H(T('电子邮件')) ?></label>
                    <input type="text" class="form-control" id="email" name="email" autocomplete="off" value="<?= $form['_errors'] ? H($form['email']) : H($user->email)  ?>" >
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group label-floating is-empty">
                    <label for="group_name" class="control-label"><?= H(T('单位名称')) ?></label>
                    <input type="text" class="form-control" id="group_name" name="group_name" autocomplete="off" value="<?= $form['_errors'] ? H($form['group_name']) : H($user->group_name) ?>" >
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group label-floating is-empty">
                    <?php if (isset($form['_errors']['type'])) { ?>
                    <span class="badge badge-danger pull-right">
                        <?= H($form['_errors']['type']) ?>
                    </span>
                    <?php } ?>
                    <label class="control-label" for="type"><?= H('人员类型') ?></label>
                    <?php $type = $form['_errors'] ? $form['type'] : (int)$user->type; ?>
                    <select class="selectpicker form-control <?= isset($form['_errors']['type']) ? 'is-invalid' : '' ?>" name="type" id="type" size="1">
                        <?php foreach (\Gini\ORM\User::$TYPE as $k => $v): ?>
                            <option value="<?= T($k) ?>" <?= $type == $k ? "selected" : '' ?>><?= T($v) ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="is_admin" <?= ($form['_errors'] ? $form['is_admin'] : $user->is_admin) ? 'checked="checked"' : '' ?> > <?= T('管理员') ?>
                    </label>
                    <label>
                        <input type="checkbox" name="is_runner" <?= ($form['_errors'] ? $form['is_runner'] : $user->is_runner) ? 'checked="checked"' : '' ?>> <?= T('合同工') ?>
                    </label>
                </div>
            </div>
        </div>
        </form>
    </div>
    <div class="modal-footer">
        <div class="col-md-12">
            <button class="btn btn-save btn-raised" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times fa-fw "></i><?= H(T('关闭')) ?></button>
            <button class="btn btn-ok btn-raised" form="add-user-form" type="submit"><i class="fa fa-save fa-fw"></i> <?= H(T('保存')) ?></button>
        <div class="row">
    </div>
</div></div>
</div>
<script data-ajax="true">
require(['main'], function($){

    var $modal = $('#add-user-modal');
    $modal
    .on('hidden.bs.modal', function(){
        $modal.remove();
    })
    .modal();

    $('#add-user-form').on('ajax-success', function(){
        $modal
        .removeAttr('id').modal('hide')
        .find('[id]').removeAttr('id');
    });

    require(['bootstrap-select', 'css!../css/bootstrap-select'], function(){
        $('.selectpicker').selectpicker()
    })
});