<div class="container-fluid">
    <div class="card text-left bg-light">
        <div class="card-header">
            <?= T('估价机构信息') ?>
        </div>
        <div class="card-body">
            <?php
                $true_group = (array)Hub('template.group');
                $group = (array)\Gini\Config::get('project.group');
            ?>
            <form id="group-info-form" method="POST" action="<?= URL('/mine')?>">
                <div class="form-group row">
                    <label for="name" class="col-sm-2 col-form-label">名称</label>
                    <div class="col-sm-10">
                        <input type="text" name="name" class="form-control" id="name" placeholder="<?= $group['name'] ?>" value="<?= $true_group['name']?>" />
                    </div>
                </div>
                <div class="form-group row">
                    <label for="address" class="col-sm-2 col-form-label">住所</label>
                    <div class="col-sm-10">
                        <input type="text" name="address" class="form-control" id="address" placeholder="<?= $group['address'] ?>" value="<?= $true_group['address']?>" />
                    </div>
                </div>
                <div class="form-group row">
                    <label for="owner" class="col-sm-2 col-form-label">法定代表人</label>
                    <div class="col-sm-10">
                        <input type="text" name="owner" class="form-control" id="owner" placeholder="<?= $group['owner'] ?>" value="<?= $true_group['owner']?>" />
                    </div>
                </div>
                <div class="form-group row">
                    <label for="level" class="col-sm-2 col-form-label">资质等级</label>
                    <div class="col-sm-10">
                        <input type="text" name="level" class="form-control" id="level" placeholder="<?= $group['level'] ?>" value="<?= $true_group['level']?>" />
                    </div>
                </div>
                <div class="form-group row">
                    <label for="number" class="col-sm-2 col-form-label">资质证书编号</label>
                    <div class="col-sm-10">
                        <input type="text" name="number" class="form-control" id="number" placeholder="<?= $group['number'] ?>" value="<?= $true_group['number']?>" />
                    </div>
                </div>
            </form>
        </div>
        <?php if (_G('ME')->isAllowedTo('修改', 'group')): ?>
        <div class="card-footer text-muted">
             <div class="btn-group mr-2" role="group" >
                <button form="group-info-form" type="submit" class="btn btn-primary"><i class="fa fa-edit fa-fw"></i><?= T('修改信息') ?></button>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>