<div class="slider">
    <?php $me = _G('ME'); ?>
    <ol class="breadcrumb">
        <li><a href="<?= URL('/') ?>">首页</a></li>
        <li class="active"><?= T('个人中心') ?></li>
    </ol>
    <div class="row">
        <div class="col-md-2">
            <div class="list-group">
                <a class="list-group-item <?= $type == 'info' ? 'active' : ''?>"><?= T('基本信息') ?></a>
                <a href="<?= URL('/mine/product') ?>" class="list-group-item <?= $type == 'product' ? 'active' : ''?>"><?= T('所购产品') ?></a>
                <?php if($me->isAllowedTo('管理')): ?>
                    <a href="<?= URL('/manage') ?>" class="list-group-item"><?= T('管理界面') ?></a>
                <?php endif; ?>
            </div>
        </div>
        <div class="col-md-10">
            <div class="mine-container">
                <h1 class="title"><span></span>基本信息</h1>
                <form method="POST" id="info-form">
                    <table class="table m">
                        <tbody>
                            <tr>
                                <td class="col-md-2 col-xs-4"><?= T('手机号') ?></td>
                                <td class="col-md-4 col-xs-8">
                                    <input class="form-control" type="text" name="phone" disabled value="<?= H($me->username) ?>" />
                                </td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td class="col-md-2 col-xs-4"><?= T('姓名') ?></td>
                                <td class="col-md-4 col-xs-8">
                                    <input class="form-control" type="text" name="name" value="<?= H($me->name) ?>" />
                                </td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td><?= T('邮箱') ?></td>
                                <td>
                                    <input class="form-control" type="text" name="email" value="<?= H($me->email) ?>" />
                                </td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td><?= T('单位名称') ?></td>
                                <td>
                                    <input class="form-control" type="text" name="group" value="<?= $me->group_name ?>" />
                                </td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td colspan="4"><button class="btn btn-primary" type="submit" name="submit-info" value="submit-info" form="info-form"><?= T('修改信息') ?></button></td>
                            </tr>
                        </tbody>
                    </table>
                </form>
                <h1 class="title"><span></span><?= T('密码信息') ?></h1>
                <form method="POST" id="password-form">
                    <table class="table m">
                        <tbody>
                            <tr>
                                <td class="col-md-2 col-xs-4"><?= T('原密码') ?></td>
                                <td class="col-md-4 col-xs-8">
                                    <div class="form-group <?= isset($form['_errors']['pwd']) ? 'has-error' : ''?>">
                                        <?php if(isset($form['_errors']['pwd'])): ?>
                                        <label class="control-label" for="pwd"><?= $form['_errors']['pwd'] ?></label>
                                        <?php endif; ?>
                                        <input id="pwd" type="password" name="pwd" class="form-control" />
                                    </div>
                                </td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td class="col-md-2 col-xs-4"><?= T('新密码') ?></td>
                                <td class="col-md-4 col-xs-8">
                                    <div class="form-group <?= isset($form['_errors']['code']) ? 'has-error' : ''?>">
                                        <?php if(isset($form['_errors']['code'])): ?>
                                        <label class="control-label" for="code"><?= $form['_errors']['code'] ?></label>
                                        <?php endif; ?>
                                        <input id="code" type="password" name="code" class="form-control" value="<?= $form['code']?>" />
                                    </div>
                                </td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td class="col-md-2 col-xs-4"><?= T('重复新密码') ?></td>
                                <td class="col-md-4 col-xs-8">
                                    <div class="form-group <?= isset($form['_errors']['re_code']) ? 'has-error' : ''?>">
                                        <?php if(isset($form['_errors']['re_code'])): ?>
                                        <label class="control-label" for="re_code"><?= $form['_errors']['re_code'] ?></label>
                                        <?php endif; ?>
                                        <input id="re_code" type="password" name="re_code" class="form-control" value="<?= $form['re_code']?>" />
                                    </div>
                                </td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td colspan="4"><button class="btn btn-primary" type="submit" name="submit-password" value="submit-password" form="password-form"><?= T('修改密码') ?></button></td>
                            </tr>
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
    <div class="hr_2"></div>
</div>