<div class="slider">
    <?php $me = _G('ME'); ?>
    <ol class="breadcrumb">
        <li><a href="<?= URL('/') ?>">首页</a></li>
        <li class="active"><?= T('个人中心') ?></li>
    </ol>
    <div class="row">
        <div class="col-md-2">
            <div class="list-group">
                <a href="<?= URL('/mine') ?>" class="list-group-item <?= $type == 'info' ? 'active' : ''?>"><?= T('基本信息') ?></a>
                <a class="list-group-item <?= $type == 'product' ? 'active' : ''?>"><?= T('所购产品') ?></a>
                <?php if($me->isAllowedTo('管理')): ?>
                    <a href="<?= URL('/manage') ?>" class="list-group-item"><?= T('管理界面') ?></a>
                <?php endif; ?>
            </div>
        </div>
        <div class="col-md-10">
            <div class="mine-container">
                <h1 class="title">
                    <span></span>购买产品信息
                </h1>
                <table class="table table-hover m">
                    <tbody>
                        <tr class="bg bg-primary">
                            <td class="hidden-xs"><?= T('产品编号') ?></td>
                            <td class="hidden-xs"><?= T('产品名称') ?></td>
                            <td><?= T('购买金额') ?></td>
                            <td><?= T('到期期限') ?></td>
                        </tr>
                    </tbody>
                    <tbody>
                        <?php if (!count($agreements)): ?>
                            <tr>
                                <td colspan="5"><p class="text-center red"><?= T('未查询到购买产品!') ?></p></td>
                            </tr>
                        <?php
                            else: foreach($agreements as $agreement): 
                        ?>
                            <tr>
                                <td class="hidden-xs"><?= H($agreement->product->number) ?></td>
                                <td class="hidden-xs"><?= H($agreement->product->title) ?></td>
                                <td><span class="red"><?= strtr('￥%amount.00', ['%amount' => $agreement->amount]) ?></span></td>
                                <td><?= date('Y-m-d', strtotime($agreement->ctime) + $agreement->product->dead_day * 86400) ?></td>
                            </tr>
                        <?php endforeach; endif;?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="hr_2"></div>
</div>