<div class="slider">
    <ol class="breadcrumb">
        <li><a href="<?= URL('/') ?>">首页</a></li>
        <li class="active"><?= T('联系我们') ?></li>
    </ol>
    <div class="news-content">
        <h1 class="title"><span></span>公司介绍</h1>
        <p class="about-content"><?= Hub('about_desc_info') ?></p>
    </div>
    <div class="hr_2"></div>
    <div class="news-content">
        <h1 class="title"><span></span>经营范围</h1>
        <p class="about-content"><?= Hub('about_desc_scope') ?></p>
    </div>
    <div class="hr_2"></div>
</div>