<div class="row">
    <div class="col-md-8">
        <ul class="footer-menu">
            <li><a href="<?= URL('/') ?>" title="煎饼理财首页" target="_blank">煎饼首页</a></li>
            <li><span>|</span></li>
            <li><a href="https://about.pingan.com/index.shtml" title="产品介绍" target="_blank">产品介绍</a></li>
            <li><span>|</span></li>
            <li><a href="https://about.pingan.com/index.shtml" title="产品介绍" target="_blank">新闻公告</a></li>
            <li><span>|</span></li>
            <li><a href="https://about.pingan.com/index.shtml" title="产品介绍" target="_blank">联系我们</a></li>
        </ul>
        <div class="copyright">
            <p><a href="http://www.miitbeian.gov.cn/" target="_blank">津ICP备16007343号</a> © 中国（集团）股份有限公司版权所有</p>
            <p>Copyright ©  ,LTD. All Rights Reserved</p>
        </div>
    </div>
    <div class="col-md-4"></div>
</div>