<div class="row">
    <div class="col-md-8">
        <ul class="footer-menu">
            <li><a href="<?= URL('/') ?>" title="煎饼理财首页" target="_blank">煎饼首页</a></li>
            <li><span>|</span></li>
            <li><a href="<?= URL('/products') ?>" title="产品介绍" target="_blank">产品介绍</a></li>
            <li><span>|</span></li>
            <li><a href="<?= URL('/news') ?>" title="产品介绍" target="_blank">新闻公告</a></li>
            <li><span>|</span></li>
            <li><a href="<?= URL('/about') ?>" title="产品介绍" target="_blank">联系我们</a></li>
        </ul>
        <div class="copyright">
            <p><a href="http://www.miitbeian.gov.cn/" target="_blank">津ICP备16007343号</a> © 天津市玉丰典瑞资产管理有限公司版权所有</p>
            <p>Copyright © YU FENG DIAN RUI ASSET MANAGEMENT (GROUP) COMPANY OF TIANJIN, LTD. All Rights Reserved</p>
        </div>
    </div>
    <div class="col-md-4">
        <img src="<?= URL('/assets/img/qrcode.png') ?>" height="86px" />
    </div>
</div>