<?php
    $errors = (array)$form['_errors'];
    if (count($errors)):
?>
<div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <?php foreach($errors as $error): ?>
        <p><i class="fa fa-warning"></i> <?= $error ?></p>
    <?php endforeach; ?>
</div>
<?php endif; ?>