<div class="slider-block">
    <?php $me = _G('ME') ?>
    <div class="login-box">
        <div class="text-center title"><?= T('煎饼理财') ?></div>
        <div class="text-center sub-title"><?= T('做您看得懂的金融') ?></div>
        <div class="text-center login-title"><?= T('登陆后您可以查看到您的') ?></div>
        <div class="text-center login-body">
            <i class="fa fa-gg fa-fw"></i>所购产品&#160;&#160;
            <i class="fa fa-usd fa-fw"></i>收益明细
        </div>
        <?php if ($me->id): ?>
            <a href="<?= URL('/mine') ?>" class="btn btn-primary btn-block"><?= T('个人中心') ?></a>
            <?php if($me->isAllowedTo('管理')): ?>
                <a href="<?= URL('/manage') ?>" class="btn btn-primary btn-block"><?= T('管理中心') ?></a>
            <?php endif; ?>
        <?php else: ?>
            <a href="<?= URL('/login/register') ?>" class="btn btn-primary btn-block"><?= T('立即注册') ?></a>
            <a href="<?= URL('/login') ?>" class="btn btn-primary btn-block"><?= T('安全登录') ?></a>
        <?php endif;?>
        <div class="button text-center">
            <i class="fa fa-phone fa-fw"></i>咨询热线：400-180-8898
        </div>
    </div>
    <div id="carousel" class="carousel slide" data-ride="carousel">
        <?php
            $basePath = APP_PATH.'/'.DATA_DIR.'/banner/';
            $imgs = [];
            foreach (new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($basePath), \RecursiveIteratorIterator::CHILD_FIRST) as $file) {
                if (!preg_match("/^\./", $file->getFileName())) {
                    $imgs[] = $file->getFileName();
                }
            }
        ?>
        <ol class="carousel-indicators">
            <?php foreach ($imgs as $k => $file): ?>
                <li data-target="#carousel" data-slide-to="<?= $k ?>" class="<?= $k == 0 ? 'active' : ''?>"></li>
            <?php endforeach; ?>    
        </ol>
        <div class="carousel-inner" role="listbox">
            <?php foreach ($imgs as $k => $file): ?>
                <div class="item <?= $k == 0 ? 'active' : ''?>">
                    <img src="<?= URL("/data/banner/{$file}") ?>" style="width: 100%; height: 100%; max-width: 100%; display: block;" />
                </div>
            <?php endforeach; ?>
        </div>
        <script>
        require(['main'], function($){
            $('.carousel').carousel({
                interval: 2000
            })
        })
        </script>
    </div>
</div>
<div class="product-list">
    <div class="row">
        <?php 
            $index_products = those('product')->whose('publish')->is(\Gini\ORM\Product::PUBLISH_YET)->orderBy('ctime', 'D')->limit(3); 
            foreach ($index_products as $key => $product):
        ?>
        <div class="col-md-4">
            <div class="product-desc">
                <h3><?= H($product->title) ?></h3>
                <em><?= H($product->rate ?: '0.00') ?>%</em>
                <div class="rate"><?= H(date('Y-m-d', strtotime($product->open_day))) ?></div>
                <p class="remark">开放日</p>
                <div class="list clearfix">
                    <div class="wrap"><span><strong><?= (int)$product->dead_day ?>天</strong> 期限</span></div>
                    <div class="line"></div>
                    <div class="wrap"><span><strong><?= H($product->purchase / 10000) ?>万</strong> 起购(元)</span></div>
                </div>
                <p class="btn-wrap">
                    <a class="btn btn-primary btn-block" href="<?= URL("/product/{$product->id}") ?>"><?= T('查看详情') ?></a>
                </p>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
</div>
<div class="products">
    <table class="table table-hover">
        <thead>
            <tr>
                <th colspan="6">
                    <div class="row">
                        <div class="col-md-6">
                            <h2 class="panel-title"><?= T('产品') ?></h2>
                        </div>
                        <div class="col-md-6 text-right">
                            <a class="a-link" href="<?= URL('/products') ?>"><?= T('查看更多') ?>&#160;<i class="fa fa-angle-double-right"></i></a>
                        </div>
                    </div>
                </th>
            </tr>
        </thead>
        <tbody>
            <?php 
                $products = those('product')->whose('publish')->is(\Gini\ORM\Product::PUBLISH_YET)->orderBy('ctime', 'D')->limit(10); 
                foreach ($products as $key => $product):
            ?>
            <tr>
                <td class="col-md-4 col-xs-6">
                    <a href="<?= URL("/product/{$product->id}") ?>"><p class="pro-name"><?= H($product->title) ?></p></a>
                </td>
                <td class="col-xs-2">
                    <p class="pro-rate"><?= H($product->rate ?: '0.00') ?>%</p>
                </td>
                <td class="col-xs-2 hidden-xs">
                    <p class="pro-openday"><?= H(date('Y-m-d', strtotime($product->open_day))) ?></p>
                    <p class="pro-remark">开放日</p>
                </td>
                <td class="col-xs-2 hidden-xs">
                    <p class="pro-data"><?= (int)$product->dead_day ?>天</p>
                    <p class="pro-remark">期限</p>
                </td>
                <td class="hidden-xs">
                    <p class="pro-data"><?= H($product->purchase) ?></p>
                    <p class="pro-remark">起购(元)</p>
                </td>
                <td class="col-xs-2">
                    <p class="pro-btn text-right">
                        <a class="btn" href="<?= URL("/product/{$product->id}") ?>"><?= T('查看详情') ?></a>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div class="card-list">
    <div class="row">
        <div class="col-xs-12 col-md-6">
            <div class="wrap news-list"> 
                <div class="panel-title">
                    <h2>新闻公告</h2><a href="<?= URL("/news")?>">查看更多&#160;<i class="fa fa-angle-double-right"></i></a>
                </div>
                <ul class="content">
                    <?php 
                        $news = those('news')->whose('type')->is(\Gini\ORM\News::TYPE_NORMAL)->orderBy('publish', 'D')->limit(5);
                        foreach ($news as $new):
                    ?>
                    <li>
                        <a href="<?= URL("/news/profile/{$new->id}") ?>"><?= H($new->title) ?><span><?= $new->publish ?></span></a>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
        <div class="col-xs-12 col-md-6">
        <div class="wrap news-list"> 
                <div class="panel-title">
                    <h2>产品公告</h2><a href="<?= URL("/news")?>">查看更多&#160;<i class="fa fa-angle-double-right"></i></a>
                </div>
                <ul class="content">
                    <?php 
                        $pnews = those('news')->whose('type')->is(\Gini\ORM\News::TYPE_PRODUCT)->orderBy('publish', 'D')->limit(5);
                        foreach ($pnews as $new):
                    ?>
                    <li>
                        <a href="<?= URL("/news/profile/{$new->id}") ?>"><?= H($new->title) ?><span><?= $new->publish ?></span></a>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</div>