<div class="slider">
    <div class="login-box">
        <div class="text-center title"><?= T('煎饼理财') ?></div>
        <div class="text-center sub-title"><?= T('您的利益，我们的心意') ?></div>
        <div class="text-center login-title"><?= T('登陆后您可以查看到您的') ?></div>
        <div class="text-center login-body">
            <i class="fa fa-gg fa-fw"></i>所购产品&#160;&#160;
            <i class="fa fa-usd fa-fw"></i>收益明细
        </div>
        <a href="<?= URL('/login/register') ?>" class="btn btn-primary btn-block"><?= T('立即注册') ?></a>
        <a href="<?= URL('/login') ?>" class="btn btn-success btn-block"><?= T('安全登录') ?></a>
        <div class="button text-center">
            <i class="fa fa-phone fa-fw"></i>咨询热线：400-180-8898
        </div>
    </div>
    <div id="carousel" class="carousel slide" data-ride="carousel">
        <?php
            $imgs = ['banner1.jpg', 'banner2.jpg', 'banner3.jpg', 'banner4.jpg'];
        ?>
        <ol class="carousel-indicators">
            <?php $num = 0; foreach ($imgs as $file): ?>
                <li data-target="#carousel" data-slide-to="<?= $num ?>" class="<?= $num ==0 ? 'active' : ''?>"></li>
            <?php $num ++; endforeach; ?>    
        </ol>
        <div class="carousel-inner" role="listbox" style="min-height: 300px;">
            <?php $num = 0; foreach ($imgs as $file): ?>
                <div class="item <?= $num ==0 ? 'active' : ''?>">
                    <img src="<?= URL("/assets/img/{$file}") ?>" style="width: 100%; height: 100%; max-width: 100%; display: block;" />
                </div>
            <?php $num ++; endforeach; ?>
        </div>
        <script>
        require(['main'], function($){
            $('.carousel').carousel({
                interval: 2000
            })
        })
        </script>
    </div>
</div>
<div class="product-list">
    <div class="row">
        <div class="col-md-4">
            <div class="product-desc">
                <h3>平安信托佳园181集合资金信托计划-24个月</h3>
                <em>固定收益</em>
                <div class="rate">8.80<small>%</small></div>
                <p class="remark">业绩比较基准</p>
                <div class="list clearfix">
                    <div class="wrap"><span><strong>24个月</strong>期限</span></div>
                    <div class="line"></div>
                    <div class="wrap"><span><strong>600万</strong>起购(元)</span></div>
                </div>
                <p class="btn-wrap">
                    <a class="btn btn-primary btn-block"><?= T('查看详情') ?></a>
                </p>
            </div>
        </div>
        <div class="col-md-4">
            <div class="product-desc">
                <h3>平安信托佳园181集合资金信托计划-24个月</h3>
                <em>固定收益</em>
                <div class="rate">8.80<small>%</small></div>
                <p class="remark">业绩比较基准</p>
                <div class="list clearfix">
                    <div class="wrap"><span><strong>24个月</strong>期限</span></div>
                    <div class="line"></div>
                    <div class="wrap"><span><strong>600万</strong>起购(元)</span></div>
                </div>
                <p class="btn-wrap">
                    <a class="btn btn-primary btn-block"><?= T('查看详情') ?></a>
                </p>
            </div>
        </div>
        <div class="col-md-4">
            <div class="product-desc">
                <h3>平安信托佳园181集合资金信托计划-24个月</h3>
                <em>固定收益</em>
                <div class="rate">8.80<small>%</small></div>
                <p class="remark">业绩比较基准</p>
                <div class="list clearfix">
                    <div class="wrap"><span><strong>24个月</strong>期限</span></div>
                    <div class="line"></div>
                    <div class="wrap"><span><strong>600万</strong>起购(元)</span></div>
                </div>
                <p class="btn-wrap">
                    <a class="btn btn-primary btn-block"><?= T('查看详情') ?></a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="products">
    <table class="table table-hover">
        <thead>
            <tr>
                <th colspan="6">
                    <div class="row">
                        <div class="col-md-6">
                            <h2 class="panel-title"><?= T('产品') ?></h2>
                        </div>
                        <div class="col-md-6 text-right">
                            <a class="a-link"><?= T('查看更多') ?>&#160;<i class="fa fa-angle-double-right"></i></a>
                        </div>
                    </div>
                </th>
            </tr>
        </thead>
        <tbody>
            <?php for($num=0; $num <= 8; $num++): ?>
            <tr>
                <td class="col-md-4">
                    <a><p class="pro-name">煎饼理财·开元6号集合资金信托计划-685天</p></a>
                </td>
                <td>
                    <p class="pro-type">固定收益</p>
                </td>
                <td>
                    <p class="pro-data red">
                        <strong>8.60<small>%</small></strong>
                    </p>
                    <p class="pro-remark">业绩比较基准</p>
                </td>
                <td>
                    <p class="pro-data">685天 </p>
                    <p class="pro-remark">期限</p>
                </td>
                <td>
                    <p class="pro-data">300万</p>
                    <p class="pro-remark">起购(元)</p>
                </td>
                <td>
                    <p class="pro-btn text-right">
                        <a class="btn"><?= T('查看详情') ?></a>
                    </div>
                </td>
            </tr>
            <?php endfor; ?>
        </tbody>
    </table>
</div>
<div class="card-list">
    <div class="row">
        <div class="col-md-6">
            <div class="wrap news-list"> 
                <div class="panel-title">
                    <h2>新闻公告</h2><a>查看更多&#160;<i class="fa fa-angle-double-right"></i></a>
                </div>
                <ul class="content">	
                    <li>
                        <a>平安信托有限责任公司简介<span>2018-05-08</span></a>
                    </li>
                    <li>
                        <a>平安信托有限责任公司简介<span>2018-05-08</span></a>
                    </li>
                    <li>
                        <a>平安信托有限责任公司简介<span>2018-05-08</span></a>
                    </li>
                    <li>
                        <a>平安信托有限责任公司简介<span>2018-05-08</span></a>
                    </li>
                    <li>
                        <a>平安信托有限责任公司简介<span>2018-05-08</span></a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-6">
        <div class="wrap news-list"> 
                <div class="panel-title">
                    <h2>产品公告</h2><a>查看更多&#160;<i class="fa fa-angle-double-right"></i></a>
                </div>
                <ul class="content">	
                    <li>
                        <a>平安财富鲲鹏八期集合资金信托计划延期通知<span>2018-09-08</span></a>
                    </li>
                    <li>
                        <a>平安财富鲲鹏八期集合资金信托计划延期通知<span>2018-05-08</span></a>
                    </li>
                    <li>
                        <a>平安财富鲲鹏八期集合资金信托计划延期通知<span>2018-05-08</span></a>
                    </li>
                    <li>
                        <a>平安财富鲲鹏八期集合资金信托计划延期通知<span>2018-05-08</span></a>
                    </li>
                    <li>
                        <a>平安财富鲲鹏八期集合资金信托计划延期通知<span>2018-05-08</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>