<div class="slider-block">
    <?php $me = _G('ME') ?>
    <div class="login-box">
        <div class="text-center title"><?= T('煎饼理财') ?></div>
        <div class="text-center sub-title"><?= T('您的利益，我们的心意') ?></div>
        <div class="text-center login-title"><?= T('登陆后您可以查看到您的') ?></div>
        <div class="text-center login-body">
            <i class="fa fa-gg fa-fw"></i>所购产品&#160;&#160;
            <i class="fa fa-usd fa-fw"></i>收益明细
        </div>
        <?php if ($me->id): ?>
            <a href="<?= URL('/mine') ?>" class="btn btn-success btn-block"><?= T('个人中心') ?></a>
        <?php else: ?>
            <a href="<?= URL('/login/register') ?>" class="btn btn-primary btn-block"><?= T('立即注册') ?></a>
            <a href="<?= URL('/login') ?>" class="btn btn-primary btn-block"><?= T('安全登录') ?></a>
        <?php endif;?>
        <div class="button text-center">
            <i class="fa fa-phone fa-fw"></i>咨询热线：400-180-8898
        </div>
    </div>
    <div id="carousel" class="carousel slide" data-ride="carousel">
        <?php
            $imgs = ['banner1.jpg', 'banner2.jpg', 'banner3.jpg', 'banner4.jpg'];
        ?>
        <ol class="carousel-indicators">
            <?php $num = 0; foreach ($imgs as $file): ?>
                <li data-target="#carousel" data-slide-to="<?= $num ?>" class="<?= $num ==0 ? 'active' : ''?>"></li>
            <?php $num ++; endforeach; ?>    
        </ol>
        <div class="carousel-inner" role="listbox" style="height: 300px;">
            <?php $num = 0; foreach ($imgs as $file): ?>
                <div class="item <?= $num ==0 ? 'active' : ''?>">
                    <img src="<?= URL("/assets/img/{$file}") ?>" style="width: 100%; height: 100%; max-width: 100%; display: block;" />
                </div>
            <?php $num ++; endforeach; ?>
        </div>
        <script>
        require(['main'], function($){
            $('.carousel').carousel({
                interval: 2000
            })
        })
        </script>
    </div>
</div>
<div class="product-list">
    <div class="row">
        <?php 
            $index_products = those('product')->orderBy('ctime', 'D')->limit(3); 
            foreach ($index_products as $key => $product):
        ?>
        <div class="col-md-4">
            <div class="product-desc">
                <h3><?= H($product->title) ?></h3>
                <div class="rate">8.80<small>%</small></div>
                <p class="remark">业绩比较基准</p>
                <div class="list clearfix">
                    <div class="wrap"><span><strong><?= (int)$product->dead_day ?>天</strong>期限</span></div>
                    <div class="line"></div>
                    <div class="wrap"><span><?= H($product->purchase) ?></span></div>
                </div>
                <p class="btn-wrap">
                    <a class="btn btn-primary btn-block" href="<?= URL("/product/{$product->id}") ?>"><?= T('查看详情') ?></a>
                </p>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
</div>
<div class="products">
    <table class="table table-hover">
        <thead>
            <tr>
                <th colspan="6">
                    <div class="row">
                        <div class="col-md-6">
                            <h2 class="panel-title"><?= T('产品') ?></h2>
                        </div>
                        <div class="col-md-6 text-right">
                            <a class="a-link" href="<?= URL('/products') ?>"><?= T('查看更多') ?>&#160;<i class="fa fa-angle-double-right"></i></a>
                        </div>
                    </div>
                </th>
            </tr>
        </thead>
        <tbody>
            <?php 
                $products = those('product')->orderBy('ctime', 'D')->limit(10); 
                foreach ($products as $key => $product):
            ?>
            <tr>
                <td class="col-md-4 col-xs-6">
                    <a href="<?= URL("/product/{$product->id}") ?>"><p class="pro-name"><?= H($product->title) ?></p></a>
                    <span class="tag-in-table-title">销售中</span>
                </td>
                <td class="col-xs-2 hidden-xs">
                    <p class="pro-type">固定收益</p>
                </td>
                <td class="col-xs-2 hidden-xs">
                    <p class="pro-data"><?= (int)$product->dead_day ?>天</p>
                    <p class="pro-remark">期限</p>
                </td>
                <td class="hidden-xs">
                    <p class="pro-remark"><?= H($product->purchase) ?></p>
                </td>
                <td class="col-xs-2">
                    <p class="pro-btn text-right">
                        <a class="btn" href="<?= URL("/product/{$product->id}") ?>"><?= T('查看详情') ?></a>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div class="card-list">
    <div class="row">
        <div class="col-md-6">
            <div class="wrap news-list"> 
                <div class="panel-title">
                    <h2>新闻公告</h2><a href="<?= URL("/news")?>">查看更多&#160;<i class="fa fa-angle-double-right"></i></a>
                </div>
                <ul class="content">
                    <?php 
                        $news = those('news')->orderBy('publish', 'D')->limit(5);
                        foreach ($news as $new):
                    ?>
                    <li>
                        <a href="<?= URL("/news/profile/{$new->id}") ?>"><?= H($new->title) ?><span><?= $new->publish ?></span></a>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
        <div class="col-md-6">
        <div class="wrap news-list"> 
                <div class="panel-title">
                    <h2>产品公告</h2><a>查看更多&#160;<i class="fa fa-angle-double-right"></i></a>
                </div>
                <ul class="content">	
                    <li>
                        <a>煎饼财富鲲鹏八期集合资金信托计划延期通知<span>2018-09-08</span></a>
                    </li>
                    <li>
                        <a>煎饼财富鲲鹏八期集合资金信托计划延期通知<span>2018-05-08</span></a>
                    </li>
                    <li>
                        <a>煎饼财富鲲鹏八期集合资金信托计划延期通知<span>2018-05-08</span></a>
                    </li>
                    <li>
                        <a>煎饼财富鲲鹏八期集合资金信托计划延期通知<span>2018-05-08</span></a>
                    </li>
                    <li>
                        <a>煎饼财富鲲鹏八期集合资金信托计划延期通知<span>2018-05-08</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>