<sidebar class="navbar bg-dark" id="sidebar-nav" role="navigation">
    <?php $me = _G('ME'); ?>
    <ul class="nav navbar-nav navbar-left sidebar-nav"  style="height: 100%">
        <li class="nav-open text-white text-center">
            <i class="fa fa-user fa-2x fa-fw"></i>
            <h6><?= $me->name; ?></h6>
        </li>
        <?php if ($me->isAllowedTo('查看', 'project')): ?>
        <li class="<?= 'project' == $selected ? 'active' : ''; ?>">
            <a href="<?= URL('/project'); ?>" class="text-white userList" data-toggle="tooltip" data-placement="right" data-original-title="<?= H(T('项目管理')); ?>">
                <i class="fa fa-sitemap"></i><span style="padding-left: 8px;"><?= H(T('项目管理')); ?></span>
            </a>
        </li>
        <?php endif; ?>
        <?php if ($me->isAllowedTo('查看', 'template')): ?>
        <li class="<?= 'template' == $selected ? 'active' : ''; ?>">
            <a href=<?= URL('/template'); ?> class="text-white" data-toggle="tooltip" data-placement="right" data-original-title="<?= H(T('模板信息')); ?>">
                <i class="fa fa-clone"></i><span style="padding-left: 8px;"><?= H(T('模板信息')); ?></span>
            </a>
        </li>
        <?php endif; ?>
        <?php if ($me->isAllowedTo('查看档案', 'project')): ?>
        <li class="<?= 'record' == $selected ? 'active' : ''; ?>">
            <a href=<?= URL('/record'); ?> class="text-white userList" data-toggle="tooltip" data-placement="right" data-original-title="<?= H(T('项目管理')); ?>">
                <i class="fa fa-folder"></i><span style="padding-left: 8px;"><?= H(T('档案管理')); ?></span>
            </a>
        </li>
        <?php endif; ?>
        <li class="<?= 'user' == $selected ? 'active' : ''; ?>">
            <a href="<?= URL('/user'); ?>" class="text-white userList" data-toggle="tooltip" data-placement="right" data-original-title="<?= H(T('用户管理')); ?>">
                <i class="fa fa-user"></i><span style="padding-left: 8px;"><?= H(T('用户管理')); ?></span>
            </a>
        </li>
        <?php if ($me->isAllowedTo('查看', 'role')): ?>
        <li class="<?= 'role' == $selected ? 'active' : ''; ?>">
            <a href=<?= URL('/role'); ?> class="text-white userList" data-toggle="tooltip" data-placement="right" data-original-title="<?= H(T('权限管理')); ?>">
                <i class="fa fa-group"></i><span style="padding-left: 8px;"><?= H(T('权限管理')); ?></span>
            </a>
        </li>
        <?php endif; ?>
        <?php if ($me->isAllowedTo('查看', 'group')): ?>
        <li class="<?= 'mine' == $selected ? 'active' : ''; ?>">
            <a href=<?= URL('/mine'); ?> class="text-white" data-toggle="tooltip" data-placement="right" data-original-title="<?= H(T('权限管理')); ?>">
                <i class="fa fa-book"></i><span style="padding-left: 8px;"><?= H(T('机构信息')); ?></span>
            </a>
        </li>
        <?php endif; ?>
    </ul>
</sidebar>